### PR TITLE
replace Anchore Engine with grype

### PR DESCRIPTION
**Pull request by markysoft**
update node.js 12 version
add grype exclusions for node 12, 14 and 16

### CODE REVIEW

**Comment by PriceChild** [comment]
@markysoft What're your thoughts on adding --only-fixed to the grype invocation?
I guess we do care about vulnerabilities that we can't do anything about... but would we actually do anything about it?

**Comment by PriceChild** [comment]
> @markysoft What're your thoughts on adding --only-fixed to the grype invocation? I guess we do care about vulnerabilities that we can't do anything about... but would we actually do anything about it?

In https://github.com/DEFRA/defra-docker-java/pull/8 I've added that flag to the exclude list, so if it disappears vulnerabilities will fail the build again.

Still tempted by the idea of adding a global "ignore wont-fix" to it though. Probably a better idea that --only-fixed.

**Comment by markysoft** [comment]
> 

Be interested to see how that approach works out, for now I'd prefer to leave this as is until I understand the new features of Grype better.

**Review by PriceChild — APPROVED** [review]

**Review by paulsimonandrews — APPROVED** [review]
LGTM

**Pull request merged**
